-- 3
SELECT FIRSTNAME,LASTNAME,HIREDATE FROM [DBO].[EMPLOYEES] WHERE TITLE = 'SALES REPRESENTATIVE';

-- 4
SELECT FIRSTNAME,LASTNAME,HIREDATE FROM [DBO].[EMPLOYEES] WHERE TITLE = 'SALES REPRESENTATIVE' AND COUNTRY='USA';

-- 5
SELECT ORDERID, ORDERDATE FROM [DBO].[ORDERS] WHERE EMPLOYEEID = 5

-- 6

SELECT SUPPLIERID, CONTACTNAME, CONTACTTITLE FROM [DBO].[SUPPLIERS] WHERE CONTACTTITLE != 'MARKETING MANAGER'

-- 7
SELECT PRODUCTID, PRODUCTNAME FROM [DBO].[PRODUCTS] WHERE PRODUCTNAME LIKE '%QUESO%'

-- 8 
SELECT ORDERID, CUSTOMERID, SHIPCOUNTRY FROM [DBO].[ORDERS] WHERE SHIPCOUNTRY IN ('FRANCE', 'BELGIUM')

-- 9
SELECT ORDERID, CUSTOMERID, SHIPCOUNTRY FROM [DBO].[ORDERS] WHERE SHIPCOUNTRY IN ('BRAZIL', 'MEXICO','ARGENTINA','VENEZUELA')

-- 10


SELECT FIRSTNAME, LASTNAME, TITLE, BIRTHDATE FROM [DBO].[EMPLOYEES] ORDER BY BIRTHDATE

-- 11 

SELECT FIRSTNAME, LASTNAME, TITLE, CONVERT(DATE, BIRTHDATE) FROM [DBO].[EMPLOYEES] ORDER BY BIRTHDATE

-- 12

SELECT FirstName, LASTNAME, CONCAT(FIRSTNAME,' ',LASTNAME) AS FULL_NAME FROM [dbo].Employees

-- 13
SELECT ORDERID, PRODUCTID, UNITPRICE, QUANTITY, (UnitPrice*Quantity) AS TOTALPRICE FROM [dbo].[OrderDETAILS]

-- 14
SELECT COUNT(1) AS TOTALCUSTOMERS FROM DBO.Customers

-- 15
	-- MY APPROACH
SELECT TOP 1 ORDERDATE AS FIRSTORDER FROM DBO.ORDERS ORDER BY ORDERDATE

	-- BOOK's APPROACH
SELECT MIN(ORDERDATE) AS FIRSTORDER FROM DBO.ORDERS

-- 16
SELECT COUNTRY FROM DBO.CUSTOMERS GROUP BY COUNTRY

-- 17

SELECT * FROM [dbo].[Customers]
SELECT CONTACTTITLE, COUNT(CONTACTTITLE) AS TOTAL_CONTACT_TITLE FROM [dbo].[Customers] GROUP BY CONTACTTITLE ORDER BY TOTAL_CONTACT_TITLE DESC;

-- 18 
SELECT PR.PRODUCTID, PR.PRODUCTNAME, SP.COMPANYNAME 
FROM DBO.PRODUCTS PR 
LEFT JOIN DBO.Suppliers SP 
			ON PR.SupplierID=SP.SupplierID

-- 19
SELECT ORD.ORDERID, ORD.ORDERDATE, SH.COMPANYNAME FROM ORDERS ORD
LEFT JOIN SHIPPERS SH
ON ORD.ShipVia = SH.SHIPPERID 
WHERE ORD.ORDERID > 10270

-- 20
SELECT C.CATEGORYNAME, COUNT(PR.PRODUCTNAME) AS TOTAL_PRODUCTS 
FROM PRODUCTS PR
LEFT JOIN CATEGORIES C
ON PR.CATEGORYID = C.CATEGORYID
GROUP BY C.CATEGORYNAME

-- 21
SELECT COUNTRY, CITY, COUNT(CUSTOMERID) AS TOTAL_CUSTOMERS FROM CUSTOMERS GROUP BY Country, CITY ORDER BY TOTAL_CUSTOMERS DESC

-- 22
SELECT ProductID, ProductName, UnitsInStock,ReorderLevel FROM PRODUCTS WHERE UNITSINSTOCK <= REORDERLEVEL ORDER BY ProductID

-- 23
SELECT ProductID, ProductName, UnitsInStock, UnitsOnOrder, ReorderLevel, Discontinued
FROM PRODUCTS
WHERE (UNITSINSTOCK + UnitsOnOrder) <= REORDERLEVEL
AND Discontinued = 0
ORDER BY ProductID

-- 24 **  -- Good to revise because we used case statement in ORDER BY clause
SELECT CUSTOMERID, COMPANYNAME, REGION
FROM CUSTOMERS 
ORDER BY CASE WHEN REGION IS NULL THEN 1
ELSE 0 END ASC, 
REGION ASC,
COMPANYNAME ASC

-- 25
SELECT * FROM ORDERS

SELECT TOP 3 SHIPCOUNTRY,AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS GROUP BY SHIPCOUNTRY 
ORDER BY AVERAGEFREIGHT DESC

-- 26
SELECT TOP 3 SHIPCOUNTRY,AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS
WHERE YEAR(ORDERDATE)=2015
GROUP BY SHIPCOUNTRY 
ORDER BY AVERAGEFREIGHT DESC

	-- Book's approach
	SELECT TOP 3 SHIPCOUNTRY,AVG(FREIGHT) AS AVERAGEFREIGHT 
	FROM ORDERS
	WHERE CONVERT(date, OrderDate) BETWEEN '2015-01-01' AND '2015-12-31'
	GROUP BY SHIPCOUNTRY 
	ORDER BY AVERAGEFREIGHT DESC
	
	-- Query plan was same for both the above queries


-- 27
-- Need to check solution

-- 28
/* Rough Work
select max(OrderDate) from orders

select top 1 orderdate from orders order by orderdate desc


select dateadd(month, -12, (select max(OrderDate) from orders))
*/

SELECT TOP 3 SHIPCOUNTRY,AVG(FREIGHT) AS AVERAGEFREIGHT 
FROM ORDERS
WHERE orderdate between (select dateadd(month, -12, (select max(OrderDate) from orders))) and (select max(OrderDate) from orders)
GROUP BY SHIPCOUNTRY 
ORDER BY AVERAGEFREIGHT DESC

-- 29

WITH CTE_1 AS -- join between employee and orders table
(SELECT EMP.EmployeeID, EMP.LastName, ORD.OrderID 
FROM EMPLOYEES EMP
LEFT JOIN ORDERS ORD
ON EMP.EMPLOYEEID = ORD.EmployeeID),

CTE_2 AS  -- join between cte_1 and order_details table
(
SELECT CT.EmployeeID, CT.LastName, CT.OrderID, OD.ProductID, OD.Quantity
FROM CTE_1 AS CT
LEFT JOIN OrderDetails OD
ON OD.OrderID = CT.ORDERID
)

-- join between cte_2 and products table
select EmployeeID, LastName, OrderID, PR.PRODUCTNAME, Quantity 
from CTE_2 AS CT LEFT JOIN Products AS PR
ON CT.ProductID = PR.ProductID


-- 30
SELECT CUS.CUSTOMERID,  ORD.CustomerID
FROM CUSTOMERS CUS LEFT OUTER JOIN ORDERS ORD
ON CUS.CustomerID = ORD.CustomerID
WHERE ORD.CustomerID IS NULL

-- 31
WITH CTE_1 AS 
(SELECT EmployeeID, CustomerID FROM ORDERS WHERE EmployeeID = 4)

SELECT CUS.CustomerID,CTE_1.CUSTOMERID FROM CUSTOMERS CUS LEFT JOIN CTE_1 ON CUS.CustomerID = CTE_1.CUSTOMERID WHERE CTE_1.CUSTOMERID IS NULL

----------- ADVANCED PROBLEMS -----------

-- 32
SELECT ORD.CustomerID, CUS.CompanyName, ORD.OrderID, TOTALORDERAMOUNT = SUM(OD.QUANTITY*OD.UNITPRICE)
FROM ORDERS ORD
LEFT JOIN CUSTOMERS CUS ON ORD.CustomerID = CUS.CustomerID
LEFT JOIN OrderDetails OD ON ORD.OrderID = OD.OrderID
WHERE ORD.OrderDate > '20160101' AND OrderDate < '20170101'
GROUP BY ORD.CustomerID, ORD.OrderID, CUS.CompanyName
HAVING SUM(OD.QUANTITY*OD.UNITPRICE)>10000
ORDER BY TOTALORDERAMOUNT DESC


-- 33
SELECT ORD.CustomerID, CUS.CompanyName,TOTALORDERAMOUNT = SUM(OD.QUANTITY*OD.UNITPRICE)
FROM ORDERS ORD
LEFT JOIN CUSTOMERS CUS ON ORD.CustomerID = CUS.CustomerID
LEFT JOIN OrderDetails OD ON ORD.OrderID = OD.OrderID
WHERE ORD.OrderDate > '20160101' AND OrderDate < '20170101'
GROUP BY ORD.CustomerID, CUS.CompanyName
HAVING SUM(OD.QUANTITY*OD.UNITPRICE) > 15000
ORDER BY TOTALORDERAMOUNT DESC